export const getImgFilename = (skill) =>
  skill
    .split(' ')
    .map((word) => word[0].toUpperCase() + word.slice(1))
    .join('');

export const Rune = [
  'Rune Weapon',
  'Runeword: Feather',
  'Rune of Life',
  'Magical Charge',
  'Sacred Rage',
  'Thunder Strike',
  'Runic Mines',
  'Frightening Power',
  'Runeword: Explode',
  'Unleash',
  'Menhir Wall',
  'Energy Drain',
  'Runeword: Burn',
  'Seal of Fate',
  'Reckless Offense',
  'Runeword: Absorb',
  'Freezing Mines',
  'Transmutation',
  'Energy Armor',
  'Aftershock',
  'Guardian Stones',
  'Rune Storm',
  'Rune Field',
];

export const Rogue = [
  'Calculated Strike',
  'Lucky Hit',
  'Blade Honing',
  'Envenom Weapon',
  'Nightshade',
  'Toxin Distillation',
  'Mandrake',
  'Throwing Knife',
  'Flurry of Knives',
  'Disarm Traps',
  'Flash Powder',
  'Open Wound',
  'Lay Trap',
  'Rapid Construction',
  'Improved Firing Mechanism',
  'Poison Gas Bomb',
  'Shrapnel',
  'Poison Mayhem',
  'Lethal Strike',
  'Mortal Wound',
  'Anatomy',
  'Blade Barrier',
];

export const Defense = [
  'Concussive Blow',
  'Battle Awareness',
  'Batter',
  'Armor Handling',
  'Adrenaline',
  'Rally',
  'Quick Recovery',
  'Shield Smash',
  'Resilience',
  'Focus',
  'Shield Charge',
  'Inspiration',
  'Rend Armor',
  'Disable',
  'Defensive Reaction',
  'Iron Will',
  'Disruption',
  'Defiance',
  'Colossus Form',
  'Pulverize',
  'Perfect Block',
  'Unyielding Phalanx',
];
